#
# gp-angular-devenv
# Copyright (c) 2023, Greg PFISTER. MIT License.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

version: '3.9'

# Services
services:
  gp-angular-devenv:
    container_name: gp-angular-devenv
    user: vscode
    privileged: true
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ..:/workspace
      - gp-angular-devenv-home:/home
      - gp-angular-devenv-docker-data:/var/lib/docker
    networks:
      - gp-angular-devenv-net

volumes:
  gp-angular-devenv-home:
    name: gp-angular-devenv-home
  gp-angular-devenv-docker-data:
    name: gp-angular-devenv-docker-data

networks:
  gp-angular-devenv-net:
    name: gp-angular-devenv-net
